-- =============================================================================
-- V7 — AI, Nutrition & Recipes
-- Backs the five hero features (PRD §5):
--   1. Smart Fridge AI      -> fridge_scans, fridge_scan_items
--   2. Smart Cart Nutrition -> nutrition_facts (V2) + cart_nutrition_summary view
--   3. Recommendations      -> recommendation_rules
--   4. Weekly Meal Planner  -> meal_plans, meal_plan_entries
--   5. AI Pantry            -> pantry_items
-- =============================================================================

-- -----------------------------------------------------------------------------
-- recipes
-- -----------------------------------------------------------------------------
CREATE TABLE recipes (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title          TEXT        NOT NULL,
    slug           TEXT        NOT NULL,
    description    TEXT,
    cuisine        TEXT,
    image_url      TEXT,
    prep_minutes   INT,
    cook_minutes   INT,
    servings       INT         NOT NULL DEFAULT 2,
    difficulty     TEXT        NOT NULL DEFAULT 'EASY',
    -- SEED = curated by us; AI = generated by Gemini. AI recipes are unreviewed
    -- content: we must be able to tell them apart before putting them on a page.
    source         TEXT        NOT NULL DEFAULT 'SEED',
    is_published   BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Denormalised per-serving nutrition, computed from recipe_ingredients.
    calories_per_serving NUMERIC(9,3),

    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     UUID,
    updated_by     UUID,
    deleted_at     TIMESTAMPTZ,
    version        BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT recipes_slug_chk       CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT recipes_source_chk     CHECK (source IN ('SEED', 'AI', 'USER')),
    CONSTRAINT recipes_difficulty_chk CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT recipes_servings_chk   CHECK (servings > 0),
    CONSTRAINT recipes_time_chk       CHECK (
        (prep_minutes IS NULL OR prep_minutes >= 0) AND
        (cook_minutes IS NULL OR cook_minutes >= 0)
    )
);

CREATE UNIQUE INDEX recipes_slug_uq ON recipes (slug) WHERE deleted_at IS NULL;
CREATE INDEX recipes_published_idx ON recipes (created_at DESC)
    WHERE deleted_at IS NULL AND is_published;

ALTER TABLE recipes ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'B')
    ) STORED;
CREATE INDEX recipes_search_idx ON recipes USING GIN (search_vector);

-- -----------------------------------------------------------------------------
-- recipe_ingredients
-- variant_id is NULLABLE on purpose: a recipe calls for salt, we may not sell salt.
-- The recipe stays complete, and "missing products from the store" (PRD §5.1)
-- resolves only against what we actually stock.
-- -----------------------------------------------------------------------------
CREATE TABLE recipe_ingredients (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipe_id       UUID          NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    ingredient_name TEXT          NOT NULL,
    variant_id      UUID REFERENCES product_variants (id) ON DELETE SET NULL,
    qty             NUMERIC(10,3),
    unit            TEXT,
    -- Garnishes should not make a recipe "unmakeable" in the fridge matcher.
    is_optional     BOOLEAN       NOT NULL DEFAULT FALSE,
    position        INT           NOT NULL DEFAULT 0,
    note            TEXT,

    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_by      UUID,
    deleted_at      TIMESTAMPTZ,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT recipe_ing_qty_chk  CHECK (qty IS NULL OR qty > 0),
    CONSTRAINT recipe_ing_unit_chk CHECK (unit IS NULL OR unit IN (
        'G', 'KG', 'ML', 'L', 'PIECE', 'TSP', 'TBSP', 'CUP', 'PINCH'
    ))
);

CREATE INDEX recipe_ingredients_recipe_idx  ON recipe_ingredients (recipe_id) WHERE deleted_at IS NULL;
CREATE INDEX recipe_ingredients_variant_idx ON recipe_ingredients (variant_id)
    WHERE deleted_at IS NULL AND variant_id IS NOT NULL;
-- Fridge/pantry matching joins on the free-text name when there is no variant link.
CREATE INDEX recipe_ingredients_name_idx ON recipe_ingredients (lower(ingredient_name));

CREATE TABLE recipe_steps (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipe_id   UUID        NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    position    INT         NOT NULL,
    instruction TEXT        NOT NULL,
    image_url   TEXT,
    duration_minutes INT,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_by  UUID,
    deleted_at  TIMESTAMPTZ,
    version     BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT recipe_steps_position_chk CHECK (position > 0),
    CONSTRAINT recipe_steps_uq UNIQUE (recipe_id, position)
);

-- -----------------------------------------------------------------------------
-- meal_plans  (PRD §5.4)
-- -----------------------------------------------------------------------------
CREATE TABLE meal_plans (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    goal         TEXT        NOT NULL,
    week_start   DATE        NOT NULL,
    status       TEXT        NOT NULL DEFAULT 'DRAFT',
    target_calories_per_day INT,
    notes        TEXT,
    generated_by TEXT        NOT NULL DEFAULT 'AI',

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by   UUID,
    updated_by   UUID,
    deleted_at   TIMESTAMPTZ,
    version      BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT meal_plans_goal_chk CHECK (goal IN (
        'WEIGHT_LOSS', 'MUSCLE_GAIN', 'MAINTENANCE', 'DIABETIC_FRIENDLY',
        'HIGH_PROTEIN', 'BALANCED', 'KIDS'
    )),
    CONSTRAINT meal_plans_status_chk    CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT meal_plans_generated_chk CHECK (generated_by IN ('AI', 'USER')),
    CONSTRAINT meal_plans_calories_chk  CHECK (target_calories_per_day IS NULL OR target_calories_per_day > 0),
    -- Weeks start Monday. Without this, "week of" means different things to
    -- different rows and the planner double-books days.
    CONSTRAINT meal_plans_week_start_chk CHECK (EXTRACT(ISODOW FROM week_start) = 1)
);

CREATE UNIQUE INDEX meal_plans_user_week_uq
    ON meal_plans (user_id, week_start) WHERE deleted_at IS NULL;
CREATE INDEX meal_plans_user_idx ON meal_plans (user_id, week_start DESC) WHERE deleted_at IS NULL;

CREATE TABLE meal_plan_entries (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_plan_id  UUID        NOT NULL REFERENCES meal_plans (id) ON DELETE CASCADE,
    recipe_id     UUID REFERENCES recipes (id) ON DELETE SET NULL,
    day_of_week   SMALLINT    NOT NULL,
    meal_type     TEXT        NOT NULL,
    servings      INT         NOT NULL DEFAULT 1,
    -- Free-text fallback when the AI suggests something with no recipe row.
    custom_title  TEXT,
    is_completed  BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID,
    updated_by    UUID,
    deleted_at    TIMESTAMPTZ,
    version       BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT mpe_day_chk       CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT mpe_meal_type_chk CHECK (meal_type IN ('BREAKFAST', 'LUNCH', 'SNACK', 'DINNER')),
    CONSTRAINT mpe_servings_chk  CHECK (servings > 0),
    -- An entry must point at something: a recipe or at least a title.
    CONSTRAINT mpe_content_chk   CHECK (recipe_id IS NOT NULL OR custom_title IS NOT NULL),
    CONSTRAINT mpe_slot_uq       UNIQUE (meal_plan_id, day_of_week, meal_type)
);

CREATE INDEX mpe_plan_idx   ON meal_plan_entries (meal_plan_id) WHERE deleted_at IS NULL;
CREATE INDEX mpe_recipe_idx ON meal_plan_entries (recipe_id)    WHERE deleted_at IS NULL;

-- -----------------------------------------------------------------------------
-- pantry_items  (PRD §5.5)
-- "Consume pantry before suggesting purchases" — this table is what makes the
-- recommender stop selling someone atta they already have.
-- -----------------------------------------------------------------------------
CREATE TABLE pantry_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    ingredient_name TEXT          NOT NULL,
    variant_id      UUID REFERENCES product_variants (id) ON DELETE SET NULL,
    qty             NUMERIC(10,3) NOT NULL,
    unit            TEXT          NOT NULL DEFAULT 'PIECE',
    expiry_date     DATE,
    -- Where it came from: a delivered order, or hand-entered.
    source          TEXT          NOT NULL DEFAULT 'MANUAL',
    source_order_id UUID REFERENCES orders (id) ON DELETE SET NULL,
    consumed_at     TIMESTAMPTZ,
    expiry_notified_at TIMESTAMPTZ,

    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_by      UUID,
    deleted_at      TIMESTAMPTZ,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT pantry_qty_chk    CHECK (qty >= 0),
    CONSTRAINT pantry_unit_chk   CHECK (unit IN ('G', 'KG', 'ML', 'L', 'PIECE', 'PACK')),
    CONSTRAINT pantry_source_chk CHECK (source IN ('MANUAL', 'ORDER', 'FRIDGE_SCAN'))
);

CREATE INDEX pantry_user_idx ON pantry_items (user_id)
    WHERE deleted_at IS NULL AND consumed_at IS NULL;
-- Drives expiry reminders (PRD §5.5).
CREATE INDEX pantry_expiry_idx ON pantry_items (expiry_date)
    WHERE deleted_at IS NULL AND consumed_at IS NULL AND expiry_date IS NOT NULL;
CREATE INDEX pantry_name_idx ON pantry_items (user_id, lower(ingredient_name))
    WHERE deleted_at IS NULL AND consumed_at IS NULL;

-- -----------------------------------------------------------------------------
-- fridge_scans  (PRD §5.1)
--
-- PII WARNING: these images show the inside of a customer's home. purge_after is a
-- compliance control, not a nicety — a retention job deletes the image once it
-- passes. The default comes from the settings key ai.fridge_scan_retention_days;
-- 30 days is a placeholder until a retention policy is actually decided.
-- -----------------------------------------------------------------------------
CREATE TABLE fridge_scans (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    image_url     TEXT        NOT NULL,
    status        TEXT        NOT NULL DEFAULT 'PENDING',
    model         TEXT,
    -- Raw Gemini Vision response. Kept for debugging misdetections.
    raw_response  JSONB,
    error         TEXT,
    processed_at  TIMESTAMPTZ,
    image_purged_at TIMESTAMPTZ,
    purge_after   TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '30 days'),

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID,
    updated_by    UUID,
    deleted_at    TIMESTAMPTZ,
    version       BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT fridge_scans_status_chk CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX fridge_scans_user_idx ON fridge_scans (user_id, created_at DESC) WHERE deleted_at IS NULL;
-- The retention job's query: images past their purge date, not yet purged.
CREATE INDEX fridge_scans_purge_idx ON fridge_scans (purge_after)
    WHERE image_purged_at IS NULL;

CREATE TABLE fridge_scan_items (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scan_id        UUID          NOT NULL REFERENCES fridge_scans (id) ON DELETE CASCADE,
    detected_name  TEXT          NOT NULL,
    -- Model confidence 0..1. Low-confidence detections are shown for confirmation
    -- rather than silently trusted — a wrong ingredient poisons the recipe match.
    confidence     NUMERIC(4,3),
    quantity_guess TEXT,
    variant_id     UUID REFERENCES product_variants (id) ON DELETE SET NULL,
    confirmed_by_user BOOLEAN    NOT NULL DEFAULT FALSE,

    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     UUID,
    updated_by     UUID,
    version        BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT fsi_confidence_chk CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE INDEX fsi_scan_idx ON fridge_scan_items (scan_id);
CREATE INDEX fsi_name_idx ON fridge_scan_items (lower(detected_name));

-- -----------------------------------------------------------------------------
-- recommendation_rules  (PRD §5.3)
-- Data, not code. PRD's example is Paneer -> Peas, Capsicum, Cream. As rows, ops
-- can edit pairings without a deploy, and a future ML model can score the same
-- rows instead of replacing the mechanism.
-- -----------------------------------------------------------------------------
CREATE TABLE recommendation_rules (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trigger_variant_id   UUID REFERENCES product_variants (id) ON DELETE CASCADE,
    trigger_category_id  UUID REFERENCES categories (id)       ON DELETE CASCADE,
    suggested_variant_id UUID          NOT NULL REFERENCES product_variants (id) ON DELETE CASCADE,
    rule_type            TEXT          NOT NULL DEFAULT 'COMPLEMENT',
    -- Ranking weight when several rules fire at once.
    weight               NUMERIC(5,2)  NOT NULL DEFAULT 1.0,
    reason               TEXT,
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,

    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by           UUID,
    updated_by           UUID,
    deleted_at           TIMESTAMPTZ,
    version              BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT rec_rule_type_chk CHECK (rule_type IN (
        'COMPLEMENT', 'SUBSTITUTE', 'FREQUENTLY_BOUGHT_TOGETHER', 'UPSELL', 'RECIPE_BASED'
    )),
    CONSTRAINT rec_weight_chk CHECK (weight > 0),
    -- A rule triggers on exactly one thing: a variant or a category, never both,
    -- never neither.
    CONSTRAINT rec_trigger_chk CHECK (
        (trigger_variant_id IS NOT NULL AND trigger_category_id IS NULL) OR
        (trigger_variant_id IS NULL AND trigger_category_id IS NOT NULL)
    ),
    -- Recommending a product to itself is always a bug.
    CONSTRAINT rec_no_self_chk CHECK (
        trigger_variant_id IS NULL OR trigger_variant_id <> suggested_variant_id
    )
);

CREATE INDEX rec_rules_trigger_variant_idx ON recommendation_rules (trigger_variant_id, weight DESC)
    WHERE deleted_at IS NULL AND is_active AND trigger_variant_id IS NOT NULL;
CREATE INDEX rec_rules_trigger_category_idx ON recommendation_rules (trigger_category_id, weight DESC)
    WHERE deleted_at IS NULL AND is_active AND trigger_category_id IS NOT NULL;
CREATE UNIQUE INDEX rec_rules_variant_pair_uq
    ON recommendation_rules (trigger_variant_id, suggested_variant_id, rule_type)
    WHERE deleted_at IS NULL AND trigger_variant_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- ai_request_logs  (append-only)
-- Every Gemini call, with tokens and cost. Without this, AI spend is invisible
-- until the bill arrives — and the PRD puts AI on the hot path of five features.
-- Backs the ai.monthly_budget_inr setting.
-- -----------------------------------------------------------------------------
CREATE TABLE ai_request_logs (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID REFERENCES users (id) ON DELETE SET NULL,
    feature      TEXT          NOT NULL,
    model        TEXT          NOT NULL,
    provider     TEXT          NOT NULL DEFAULT 'GEMINI',
    tokens_in    INT,
    tokens_out   INT,
    latency_ms   INT,
    cost_inr     NUMERIC(10,4),
    status       TEXT          NOT NULL,
    error        TEXT,
    ref_type     TEXT,
    ref_id       UUID,

    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by   UUID,

    CONSTRAINT ai_log_feature_chk CHECK (feature IN (
        'FRIDGE_SCAN', 'MEAL_PLAN', 'RECIPE_GEN', 'NUTRITION_ESTIMATE',
        'RECOMMENDATION', 'SEARCH_ENHANCE'
    )),
    CONSTRAINT ai_log_status_chk CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT', 'RATE_LIMITED')),
    CONSTRAINT ai_log_tokens_chk CHECK (
        (tokens_in IS NULL OR tokens_in >= 0) AND (tokens_out IS NULL OR tokens_out >= 0)
    ),
    CONSTRAINT ai_log_cost_chk CHECK (cost_inr IS NULL OR cost_inr >= 0)
);

CREATE INDEX ai_logs_feature_idx ON ai_request_logs (feature, created_at DESC);
CREATE INDEX ai_logs_user_idx    ON ai_request_logs (user_id, created_at DESC);
-- The monthly spend rollup.
CREATE INDEX ai_logs_cost_idx    ON ai_request_logs (created_at) WHERE cost_inr IS NOT NULL;

CREATE TRIGGER ai_request_logs_append_only
    BEFORE UPDATE OR DELETE ON ai_request_logs
    FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- -----------------------------------------------------------------------------
-- Smart Cart Nutrition (PRD §5.2)
--
-- Totals the cart's nutrition by scaling each line's per-100g facts by its actual
-- weight: qty * weight_grams / basis_grams.
--
-- has_complete_data matters: if any line is missing nutrition, the total is a
-- lower bound, not a fact, and the UI must say so rather than present a confident
-- wrong number.
-- -----------------------------------------------------------------------------
CREATE VIEW cart_nutrition_summary AS
SELECT
    c.id AS cart_id,
    c.user_id,
    count(ci.id)                                             AS line_count,
    count(nf.id)                                             AS lines_with_nutrition,
    bool_and(nf.id IS NOT NULL)                              AS has_complete_data,
    sum(ci.qty * v.weight_grams)                             AS total_weight_g,
    round(sum(nf.calories_kcal   * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS calories_kcal,
    round(sum(nf.protein_g       * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS protein_g,
    round(sum(nf.fat_g           * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS fat_g,
    round(sum(nf.carbohydrates_g * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS carbohydrates_g,
    round(sum(nf.fiber_g         * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS fiber_g,
    round(sum(nf.sugar_g         * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS sugar_g,
    round(sum(nf.iron_mg         * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS iron_mg,
    round(sum(nf.vitamin_a_mcg   * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS vitamin_a_mcg,
    round(sum(nf.vitamin_c_mg    * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS vitamin_c_mg,
    round(sum(nf.vitamin_d_mcg   * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS vitamin_d_mcg,
    round(sum(nf.potassium_mg    * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS potassium_mg,
    round(sum(nf.sodium_mg       * ci.qty * v.weight_grams / nf.basis_grams)::numeric, 2) AS sodium_mg
FROM carts c
JOIN cart_items ci       ON ci.cart_id = c.id AND ci.deleted_at IS NULL
JOIN product_variants v  ON v.id = ci.variant_id
LEFT JOIN nutrition_facts nf ON nf.variant_id = v.id AND nf.deleted_at IS NULL
WHERE c.deleted_at IS NULL AND c.status = 'ACTIVE'
GROUP BY c.id, c.user_id;

-- -----------------------------------------------------------------------------
-- updated_at triggers
-- -----------------------------------------------------------------------------
CREATE TRIGGER recipes_set_updated_at BEFORE UPDATE ON recipes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER recipe_ingredients_set_updated_at BEFORE UPDATE ON recipe_ingredients
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER recipe_steps_set_updated_at BEFORE UPDATE ON recipe_steps
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER meal_plans_set_updated_at BEFORE UPDATE ON meal_plans
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER meal_plan_entries_set_updated_at BEFORE UPDATE ON meal_plan_entries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER pantry_items_set_updated_at BEFORE UPDATE ON pantry_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER fridge_scans_set_updated_at BEFORE UPDATE ON fridge_scans
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER fridge_scan_items_set_updated_at BEFORE UPDATE ON fridge_scan_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER recommendation_rules_set_updated_at BEFORE UPDATE ON recommendation_rules
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
